# Generated by Django 3.2.13 on 2022-04-30 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userauth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        default=userauth.models.generateUUID, editable=False
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("borrow", "Borrow"), ("lend", "Lend")], max_length=20
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_status",
                    models.BooleanField(default=False, verbose_name="Paid"),
                ),
                ("transaction_from_or_with", models.CharField(max_length=40)),
                ("reason", models.CharField(max_length=255)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userauth.wallet",
                    ),
                ),
            ],
        ),
    ]
