# Generated by Django 3.2.13 on 2022-04-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="wallet",
        ),
    ]
