# Generated by Django 3.2.13 on 2022-05-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userauth", "0003_transactions_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="transaction_from_or_with",
        ),
        migrations.AddField(
            model_name="transactions",
            name="transaction_with",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_with",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactions",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
