# Generated by Django 3.2.13 on 2022-05-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0004_auto_20220502_1125"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
