# Generated by Django 3.2.13 on 2022-05-08 18:44

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(default=userauth.models.generateUUID),
        ),
    ]
