# Generated by Django 3.2.13 on 2022-05-08 18:45

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_transactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(default=userauth.models.generateUUID, editable=False),
        ),
    ]
